
on :
  push:
    branches:
      - master
  


jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - name: ' be   print for content'
         run: ls
        - uses: actions/checkout@v3
        - name: ' af   print for content'
         run: ls















